sudo: required

language: bash

services:
- docker

install:
- sudo bash -ex ./.travis.setup_binfmt_misc.sh
- git clone --depth 1 git://github.com/machinekit/machinekit.git

env:
- ARCH=armhf CODENAME=wheezy
- ARCH=x86_64 CODENAME=wheezy

script:
- docker run -v $(pwd)/machinekit:/usr/src/machinekit bobvanderlinden/machinekit-build:${CODENAME}-${ARCH} /bin/bash -c "cd /usr/src/machinekit && debian/configure -p && yes | mk-build-deps -i -r && debuild"
